In [93]:
def answer_one():
    
    import pandas as pd 
    import numpy as np 
    import re

    energy = pd.read_excel('/Users/emilyvincett/Downloads/Energy+Indicators.xls', skiprows=17)
    energy = energy[0:227]
    cols_to_drop = ['Unnamed: 0', 'Unnamed: 2']
    energy.drop(['Unnamed: 0','Unnamed: 2'],axis=1,inplace=True)
    cols_to_rename = ({'Unnamed: 1':'Country',
                  "Petajoules":'Energy Supply',
                  "Gigajoules":'Energy Supply per Capita',
                  "%":"% Renewables"})
    energy.rename(cols_to_rename,axis=1,inplace=True)
    countries_to_rename = ({"Republic of Korea" : "South Korea",
                        "United States of America" : "United States",
                        "United Kingdom of Great Britain and Northern Ireland" : "United Kingdom",
                        "China, Hong Kong Special Administrative Region" : "Hong Kong",
                       "Bolivia (Plurinational State of)" : "Bolivia",
                        "Iran (Islamic Republic of)" : "Iran",
                        "Micronesia (Federated States of)" : 'Micronesia',
                        "Sint Maarten (Dutch part)" : "Sint Maarten",
                        "Venezuela (Bolivarian Republic of)" : "Venezuela"})

    energy.replace(countries_to_rename,inplace=True)
    energy["Energy Supply"] = energy['Energy Supply'] * 1000000
    energy = energy.replace('[(^.*.$)]',np.NaN,regex=True)
    energy.reset_index(drop=True)
    energy = energy.set_index('Country')


    gdp = pd.read_csv('/Users/emilyvincett/Downloads/world_bank.csv', skiprows=4)
    countries_to_rename = ({"Korea, Rep.": "South Korea", 
                        "Iran, Islamic Rep.": "Iran",
                        "Hong Kong SAR, China": "Hong Kong"})

    gdp.replace(countries_to_rename,inplace=True)
    gdp.rename({'Country Name':'Country'},axis=1,inplace=True)
    date_range = np.arange(2006,2016)

    gdp = gdp[np.append(['Country'],date_range)]
    gdp.reset_index(drop=True)
    gdp.set_index('Country')

    scimen = pd.read_excel('/Users/emilyvincett/Downloads/scimagojr-3.xlsx')
    scimen.reset_index(drop=True)
    scimen.set_index('Country')

    combo = energy.merge(gdp, left_on='Country', right_on='Country').merge(scimen, left_on='Country', right_on='Country')
    combo.set_index('Country')
    combo = combo[combo['Rank']<=15]
    return combo 

answer_one()

,Country,Energy Supply,Energy Supply per Capita,% Renewables,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
9,Australia,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,...,1.241484e+12,1.272520e+12,1.301251e+12,14,8831,8725,90765,15606,10.28,107
24,Brazil,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,...,2.409740e+12,2.412231e+12,2.319423e+12,15,8668,8596,60702,14396,7.00,86
31,Canada,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,...,1.730688e+12,1.773486e+12,1.792609e+12,6,17899,17620,215003,40930,12.01,149
35,China,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,...,7.672448e+12,8.230121e+12,8.797999e+12,1,127050,126767,597237,411683,4.70,138
54,France,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,...,2.722567e+12,2.729632e+12,2.761185e+12,9,13153,12973,130632,28601,9.93,114
57,Germany,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,...,3.567317e+12,3.624386e+12,3.685556e+12,7,17027,16831,140566,27426,8.26,126
68,India,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,...,2.051982e+12,2.200617e+12,2.367206e+12,8,15005,14841,128763,37209,8.58,115
70,Iran,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,...,4.445926e+11,4.639027e+11,NaN,13,8896,8819,57470,19125,6.46,72
74,Italy,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,...,2.040871e+12,2.033868e+12,2.049316e+12,11,10964,10794,111850,26661,10.20,106
76,Japan,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,...,5.644659e+12,5.642884e+12,5.669563e+12,3,30504,30287,223024,61554,7.31,134
125,South Korea,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,...,1.194429e+12,1.234340e+12,1.266580e+12,10,11983,11923,114675,22595,9.57,104
127,Russian Federation,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,...,1.666934e+12,1.678709e+12,1.616149e+12,5,18534,18301,34266,12422,1.85,57
138,Spain,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,...,1.357139e+12,1.375605e+12,1.419821e+12,12,9428,9330,123336,23964,13.08,115
156,United Kingdom,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,...,2.533370e+12,2.605643e+12,2.666333e+12,4,20944,20357,206091,37874,9.84,139
157,United States,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,...,1.577367e+13,1.615662e+13,1.654857e+13,2,96661,94747,792274,265436,8.20,230

In [150]:
def answer_two():
    
    import pandas as pd 
    import numpy as np 
    import re

    energy = pd.read_excel('/Users/emilyvincett/Downloads/Energy+Indicators.xls', skiprows=17)
    energy = energy[0:227]
    cols_to_drop = ['Unnamed: 0', 'Unnamed: 2']
    energy.drop(['Unnamed: 0','Unnamed: 2'],axis=1,inplace=True)
    cols_to_rename = ({'Unnamed: 1':'Country',
                  "Petajoules":'Energy Supply',
                  "Gigajoules":'Energy Supply per Capita',
                  "%":"% Renewables"})
    energy.rename(cols_to_rename,axis=1,inplace=True)

    countries_to_rename = ({"Republic of Korea" : "South Korea",
                        "United States of America" : "United States",
                        "United Kingdom of Great Britain and Northern Ireland" : "United Kingdom",
                        "China, Hong Kong Special Administrative Region" : "Hong Kong",
                       "Bolivia (Plurinational State of)" : "Bolivia",
                        "Iran (Islamic Republic of)" : "Iran",
                        "Micronesia (Federated States of)" : 'Micronesia',
                        "Sint Maarten (Dutch part)" : "Sint Maarten",
                        "Venezuela (Bolivarian Republic of)" : "Venezuela"})

    energy.replace(countries_to_rename,inplace=True)
    energy["Energy Supply"] = energy['Energy Supply'] * 1000000
    energy = energy.replace('[(^.*.$)]',np.NaN,regex=True)
    energy.reset_index(drop=True)
    energy = energy.set_index('Country')


    gdp = pd.read_csv('/Users/emilyvincett/Downloads/world_bank.csv', skiprows=4)
    countries_to_rename = ({"Korea, Rep.": "South Korea", 
                        "Iran, Islamic Rep.": "Iran",
                        "Hong Kong SAR, China": "Hong Kong"})

    gdp.replace(countries_to_rename,inplace=True)
    gdp.rename({'Country Name':'Country'},axis=1,inplace=True)
    date_range = np.arange(2006,2016)
    date_range
    gdp = gdp[np.append(['Country'],date_range)]
    gdp.reset_index(drop=True)
    gdp.set_index('Country')

    scimen = pd.read_excel('/Users/emilyvincett/Downloads/scimagojr-3.xlsx')
    scimen.reset_index(drop=True)
    scimen.set_index('Country')

    combo = energy.merge(gdp, left_on='Country', right_on='Country').merge(scimen, left_on='Country', right_on='Country')
    combo.set_index('Country')


    combo_1 = combo.shape[0]-15
    return combo_1

answer_two()

147

In [149]:
def answer_three():
    
    top15 = answer_one()
    date_range = np.arange(2006,2016).astype(str)
    top15['avgGDP'] = top15[date_range].mean(axis=1).dropna()
    top15.reset_index(drop=True)
    top15 = top15.set_index('Country')
    top15.loc['Australia','avgGDP']
    return top15['avgGDP'].sort_values(ascending=False)

answer_three()

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
Name: avgGDP, dtype: float64

In [248]:
def answer_four():
    
    top15 = answer_one()
    date_range = np.arange(2006,2016).astype(str)
    top15['avgGDP'] = top15[date_range].mean(axis=1).dropna()
    top15 = top15.sort_values(['avgGDP'],ascending=False)
    top15 = top15.reset_index(drop=True)
    top15['change'] = top15['2015'] - top15['2006']
    return top15.loc[5,'change']

answer_four()

246702696075.3999

In [254]:
def answer_five():
    top15 = answer_one()
    return top15['Energy Supply per Capita'].mean(axis=0)

answer_five()

157.6

In [282]:
def answer_six():
    
    top15 = answer_one()
    top15 = top15.reset_index(drop=True)
    position = top15['% Renewables'].idxmax()
    Country = top15.loc[position,'Country']
    Renewables = top15.loc[position, '% Renewables']
    return (Country , Renewables)

answer_six()

('Brazil', 69.64803)

In [300]:
def answer_seven():
    
    top15 = answer_one()
    top15
    top15['Citations ratio'] = top15['Self-citations']/top15['Citations']
    position = top15['Citations ratio'].idxmax()
    citations_ratio = top15.loc[position, 'Citations ratio']
    country = top15.loc[position, 'Country']
    return (country, citations_ratio)

answer_seven()

('China', 0.6893126179389422)

In [316]:
def answer_eight():
    
    top15 = answer_one()
    top15['Population'] = top15['Energy Supply']/top15['Energy Supply per Capita']
    top15 = top15.sort_values(['Population'],ascending=False)
    top15 = top15.reset_index(drop=True)
    return top15.loc[2, 'Country']

answer_eight()

'United States'

In [336]:
def answer_nine():
    
    top15 = answer_one()
    top15['Population'] = top15['Energy Supply']/top15['Energy Supply per Capita']
    top15['Citable docs per Capita'] = top15['Citable documents']/top15['Population']
    cols_to_use = (['Citable docs per Capita', 'Energy Supply per Capita'])
    top15 = top15[cols_to_use]
    correlation = top15.corr(method='pearson')
    return correlation.iloc[1]['Citable docs per Capita']

answer_nine()

0.7940010435442943

In [364]:
def answer_ten():
    
    top15 = answer_one()
    top15 = top15.reset_index(drop=True)
    top15 = top15.set_index('Country')
    median = top15['% Renewables'].median()
    top15['Above Median'] = (top15['% Renewables']>=median)
    return top15['Above Median']

answer_ten()

Country
Australia             False
Brazil                 True
Canada                 True
China                  True
France                 True
Germany                True
India                 False
Iran                  False
Italy                  True
Japan                 False
South Korea           False
Russian Federation     True
Spain                  True
United Kingdom        False
United States         False
Name: Above Median, dtype: bool